name: 'testing approvals'

on:
  workflow_dispatch:
  push:
      branches:
        - main


jobs:
  testingenv:
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          environment: dev
          image_tag: ${{ github.sha }}
          secrets: inherit
              
